export enum OtpType {
  EMAIL_VERIFICATION = "EMAIL_VERIFICATION",
  PASSWORD_RESET = "PASSWORD_RESET",
  PHONE_VERIFICATION = "PHONE_VERIFICATION",
}
export enum UserRole {
  ACTIVATED = "USER_ACTIVATED",
  NOT_ACTIVATED = "NOT_ACTIVATED",
}
